projects:
  posts-api:
    schema: apps/posts-api/src/graphql/**/*.graphql
    documents: []
    include:
      - apps/posts-api/src/**
    extensions:
      endpoints:
        local:
          url: http://localhost:3000/graphql
          headers:
            Authorization: Bearer ${env:GRAPHQL_TOKEN}
          introspect: false
  posts-app:
    schema:
      - apps/posts-api/src/graphql/**/*.graphql
      - '!apps/posts-api/src/graphql/federation.graphql'
      - apps/posts-app/mcp-apps.graphql
    documents:
      - apps/posts-app/src/**/*.{ts,tsx}
    include:
      - apps/posts-app/src/**
    exclude:
      - apps/posts-app/src/graphql/__gen__/**
  web:
    schema:
      - apps/posts-api/src/graphql/**/*.graphql
      - '!apps/posts-api/src/graphql/federation.graphql'
      - apps/web/federation.graphql
    documents:
      - apps/web/src/**/*.{ts,tsx}
    include:
      - apps/web/src/**
    exclude:
      - apps/web/src/gql/**
    extensions:
      endpoints:
        local:
          url: http://localhost:3000/graphql
          headers:
            Authorization: Bearer ${env:GRAPHQL_TOKEN}
          introspect: false
