projects:
  posts-api:
    schema: apps/posts-api/src/graphql/**/*.graphql
    include:
      - apps/posts-api/src/**
    extensions:
      endpoints:
        local:
          url: http://localhost:3000/graphql
          headers:
            Authorization: Bearer ${env:GRAPHQL_TOKEN}
          introspect: false

  web:
    schema:
      - apps/posts-api/src/graphql/**/*.graphql
      - '!apps/posts-api/src/graphql/federation.graphql'
      - apps/web/federation.graphql
    documents:
      - apps/web/src/**/*.{ts,tsx}
    include:
      - apps/web/src/**
    exclude:
      - apps/web/src/gql/**
    extensions:
      endpoints:
        local:
          url: http://localhost:3000/graphql
          headers:
            Authorization: Bearer ${env:GRAPHQL_TOKEN}
          introspect: false
