packages:
  - libs/*
  - apps/*
  - packages/*

allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true
  sharp: true

catalog:
  '@biomejs/biome': ^2.5.14
  '@graphql-tools/webpack-loader': ^7.0.1
  '@nx/js': 23.2.1
  '@nx/nest': 23.2.1
  '@nx/next': 23.2.1
  '@nx/playwright': 23.2.1
  '@nx/workspace': 23.2.1
  nx: 23.2.1
  typescript: ^6.0.3

catalogMode: strict

onlyBuiltDependencies:
  - '@swc/core'
  - esbuild
  - nx
  - sharp

overrides:
  '@better-auth/utils': 0.4.2
