export const BILLING_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_BILLING';

export const POLAR_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_POLAR';

export const POLAR_WEBHOOKS_BETTER_AUTH_PLUGIN =
  'BETTER_AUTH_PLUGIN_POLAR_WEBHOOKS';
