export const ORGANIZATION_BETTER_AUTH_PLUGIN =
  'BETTER_AUTH_PLUGIN_ORGANIZATION';

export const ADMIN_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_ADMIN';

export const JWT_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_JWT';

export const OAUTH_PROVIDER_BETTER_AUTH_PLUGIN =
  'BETTER_AUTH_PLUGIN_OAUTH_PROVIDER';

export const OPEN_API_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_OPEN_API';
