export const ADMIN_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_ADMIN';

export const JWT_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_JWT';

export const OAUTH_PROVIDER_BETTER_AUTH_PLUGIN =
  'BETTER_AUTH_PLUGIN_OAUTH_PROVIDER';

export const OPEN_API_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_OPEN_API';

export const MAGIC_LINK_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_MAGIC_LINK';

export const EMAIL_OTP_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_EMAIL_OTP';

export const TWO_FACTOR_BETTER_AUTH_PLUGIN = 'BETTER_AUTH_PLUGIN_TWO_FACTOR';

export const MULTI_SESSION_BETTER_AUTH_PLUGIN =
  'BETTER_AUTH_PLUGIN_MULTI_SESSION';
