export const BETTER_AUTH = 'BETTER_AUTH';

export const BETTER_AUTH_CONFIG = 'BETTER_AUTH_CONFIG';

export const BETTER_AUTH_ADAPTER = 'BETTER_AUTH_ADAPTER';

export const BETTER_AUTH_PLUGINS = 'BETTER_AUTH_PLUGINS';
