export const BETTER_AUTH = 'BETTER_AUTH';

export const BETTER_AUTH_ADAPTER = 'BETTER_AUTH_ADAPTER';

export const BETTER_AUTH_PLUGINS = 'BETTER_AUTH_PLUGINS';

export const BETTER_AUTH_SECONDARY_STORAGE = 'BETTER_AUTH_SECONDARY_STORAGE';
