/** biome-ignore-all lint/suspicious/noExplicitAny: ignore anys in file */
/** biome-ignore-all lint/complexity/noThisInStatic: accept using this in static because of the class transformations */
import 'reflect-metadata';

import { Expose, Transform } from 'class-transformer';
import type {
  ValidationArguments,
  ValidatorConstraintInterface,
} from 'class-validator';
import { Validate, ValidatorConstraint } from 'class-validator';
import { z } from 'zod';

import type { DECORATOR_REGISTRY_TYPE } from '../schemas/registries/decorators.registry';
import { DECORATOR_REGISTRY as GLOBAL_DECORATOR_REGISTRY } from '../schemas/registries/decorators.registry';
import type { EMBEDDED_REGISTRY_TYPE } from '../schemas/registries/embedded.registry';
import { EMBEDDED_REGISTRY } from '../schemas/registries/embedded.registry';

/**
 * Marks on the prototype that a class is a scalar value object. A symbol rather than an `instanceof`,
 * because every `ValidatedScalar` call generates a different base class: `PostId` and `TagId` share no
 * ancestor, yet both have to be recognized as scalars by whoever receives them.
 */
export const SCALAR_VALUE_OBJECT = Symbol.for('validated-dto:scalar');

/** The base generated by the mixin — a value object's "family", used by `equals`. */
const SCALAR_BASE = Symbol.for('validated-dto:scalar-base');

/** Cache of the last validation error, so `isValid()` does not re-parse on every call. */
const ISSUE_CACHE = Symbol.for('validated-dto:scalar-issues');

/** Node's `util.inspect` hook — `console.log(postId)` reads well. */
const INSPECT_CUSTOM = Symbol.for('nodejs.util.inspect.custom');

/** `true` if the value is a scalar value object generated by {@link ValidatedScalar}. */
export function isScalarValueObject(
  value: unknown,
): value is ScalarValueObject<unknown> {
  return (
    typeof value === 'object' &&
    value !== null &&
    (
      value as unknown as {
        [SCALAR_VALUE_OBJECT]: true;
      }
    )[SCALAR_VALUE_OBJECT] === true
  );
}

/**
 * The raw value behind a value object — and the value itself, when it is already raw.
 *
 * It is the unwrapping that lets `new PostId(anotherPostId)` and `new PostId('uuid')` be the same
 * call: on input, a value object accepts anything that already *is* its value.
 */
export function rawScalarValue(value: unknown): unknown {
  return isScalarValueObject(value) ? value.value : value;
}

/**
 * The `ValidatorConstraint` for a scalar's `value` field.
 *
 * The difference from the object mixin's `ZodFieldValidator` is where the schema comes from: here it
 * is read from the **instance's constructor** (`this.constructor.schema`), falling back to the
 * captured constraint only as a last resort. That is what makes a subclass overriding `static schema`
 * validate by its own rules — the hook for "extend the class to add specific rules".
 */
@ValidatorConstraint({ name: 'ZodScalarValidator', async: false })
export class ZodScalarValidator implements ValidatorConstraintInterface {
  validate(value: unknown, args: ValidationArguments): boolean {
    return this.schemaOf(args).safeParse(rawScalarValue(value)).success;
  }

  defaultMessage(args: ValidationArguments): string {
    const schema = this.schemaOf(args);
    const result = schema.safeParse(rawScalarValue(args.value));

    if (schema.description) {
      return `${schema.description} is invalid`;
    }
    if (!result.success) {
      return result.error.issues[0].message;
    }
    return 'Validation failed';
  }

  private schemaOf(args: ValidationArguments): z.ZodType {
    const fromInstance = (args.object as any)?.constructor?.schema;
    return (fromInstance ?? args.constraints[0]) as z.ZodType;
  }
}

/**
 * The value as JSON sees it. Only `Date` differs: `JSON.stringify` calls `toJSON()` **once** and
 * serializes whatever comes back without consulting its `toJSON` again — returning the raw `Date`
 * would yield `{}`.
 */
export type JsonScalar<Out> = Out extends Date ? string : Out;

/** The result of `VO.safeParse` — Zod's own shape, with the instance in place of the raw value. */
export type ScalarSafeParseResult<T> =
  | { success: true; data: T; error?: undefined }
  | { success: false; data?: undefined; error: z.ZodError };

/** The **instance** side of a scalar value object. */
export interface ScalarValueObject<Out> {
  /** The value, already normalized by the schema (trim, lowercase, coerce…). */
  readonly value: Out;
  readonly [SCALAR_VALUE_OBJECT]: true;
  /** The value as text — `String(vo)`, `` `${vo}` `` and template literals go through here. */
  toString(): string;
  /** The value ready for JSON — what makes `JSON.stringify(dto)` see the primitive. */
  toJSON(): JsonScalar<Out>;
  /** The raw value. Likewise, and what makes `vo == 'text'` and `vo1 < vo2` work. */
  valueOf(): Out;
  /** **Value** equality: two value objects of the same family holding the same value are the same. */
  equals(other: unknown): boolean;
  /** Does the current value pass the schema? */
  isValid(): boolean;
  /** The schema error for the current value, or `undefined` if it is valid. */
  validationError(): z.ZodError | undefined;
  /** Returns `this`, or throws the `ZodError` — `parse` in guard form. */
  assertValid(): this;
}

type AnyScalarConstructor = abstract new (
  ...args: any[]
) => ScalarValueObject<any>;

/** What a scalar value object class accepts constructing from. */
export type ScalarInput<Out, In> = In | ScalarValueObject<Out>;

/** The options for `VO.field()` — what this **use** of the value object adds to the field. */
export interface ScalarFieldOptions {
  /**
   * Decorators for the field on the final class (`@Field()`, `@ApiProperty()`…), applied by
   * `@InheritValidatedMetadata()`.
   *
   * Passing them makes `field()` return a **new** schema instead of the shared one: two DTOs embedding
   * the same value object with different decorators cannot share the same field.
   */
  decorators?: Array<PropertyDecorator | ClassDecorator>;
  DECORATOR_REGISTRY?: DECORATOR_REGISTRY_TYPE;
}

/**
 * The **static** side of a scalar value object. Every method uses polymorphic `this`, so
 * `PostId.parse(x)` returns `PostId` — not the anonymous base the mixin generated.
 */
export interface ScalarValueObjectStatic<
  Out,
  In,
  Schema extends z.ZodType<any, any> = z.ZodType<Out, In>,
> {
  new (value: ScalarInput<Out, In>): ScalarValueObject<Out>;

  /**
   * The schema defining the value — in its concrete type, not flattened into `ZodType`: `PostId.schema`
   * is a branded `ZodUUID`, with its methods at hand. A subclass may override it to tighten the rules
   * (but the typed path for that is {@link ScalarValueObjectStatic.narrow}).
   */
  schema: Schema;
  /** When `true`, the constructor throws instead of storing an invalid value. Default: `false`. */
  strict: boolean;

  /** Constructs with validation: returns the instance or throws `ZodError`. */
  parse<T extends AnyScalarConstructor>(
    this: T,
    value: unknown,
  ): InstanceType<T>;
  /** Constructs with validation, without throwing. */
  safeParse<T extends AnyScalarConstructor>(
    this: T,
    value: unknown,
  ): ScalarSafeParseResult<InstanceType<T>>;
  /** Wraps an **already validated** value, without going through the schema again. */
  wrap<T extends AnyScalarConstructor>(this: T, parsed: Out): InstanceType<T>;
  /** Type guard: is `value` an instance of this class (or of a subclass)? */
  is<T extends AnyScalarConstructor>(
    this: T,
    value: unknown,
  ): value is InstanceType<T>;

  /**
   * A base **with tighter rules** — the typed way to specialize a value object.
   *
   * ```ts
   * class ShortTitle extends PostTitle.narrow((title) => title.max(40, 'too short')) {}
   * ```
   *
   * The type remains that of the originating class (a `ShortTitle` *is* a `PostTitle`), and only the
   * schema changes — which is why `.brand()` does not have to be repeated, unlike what happens when
   * overriding `static schema` by hand.
   */
  narrow<T extends AnyScalarConstructor>(
    this: T,
    refine: (schema: Schema) => z.ZodType<any, any>,
  ): T;
  /** `true` if the raw value passes the schema — without constructing anything. */
  accepts(value: unknown): boolean;

  /**
   * The schema for **embedding** this value object into a DTO's `z.object` — Java's `@Embedded`.
   *
   * The field accepts the raw value (or another value object) on input and produces the instance on
   * output, and the object mixin recognizes it through `EMBEDDED_REGISTRY`: it serializes by collapsing
   * to the raw value, and deserializes by constructing the class. It is stable per class — calling it
   * twice returns the same schema.
   */
  field<T extends AnyScalarConstructor>(
    this: T,
    options?: ScalarFieldOptions,
  ): z.ZodType<InstanceType<T>, ScalarInput<Out, In>>;

  /** Copies the metadata onto a subclass — the hook behind `@InheritValidatedMetadata()`. */
  __copyMetadataToChild(childClass: any): void;
}

export interface ValidatedScalarOptions {
  /**
   * The **generated base**'s name. Almost always unnecessary: the normal path is to extend
   * (`class Email extends ValidatedDto.Scalar(schema) {}`), and then JavaScript does the naming — the
   * subclass is already called `Email`, and it is its `constructor.name` that shows up in `inspect` and
   * in messages. It is only worth passing when the base is used **without** a subclass.
   *
   * This cannot be derived from the `brand`: in Zod 4 `.brand()` returns `this` and stores nothing —
   * the argument in `.brand<'Email'>('Email')` is discarded, and the mark exists only in the type.
   */
  name?: string;
  /** Applies `@Expose()` to `value` (default `true`), like the object mixin's `exposeAll`. */
  exposeAll?: boolean;
  /** The constructor throws instead of storing an invalid value (default `false`). */
  strict?: boolean;
  DECORATOR_REGISTRY?: DECORATOR_REGISTRY_TYPE;
  EMBEDDED_REGISTRY?: EMBEDDED_REGISTRY_TYPE;
}

/** Raw value equality, covering the cases where `===` does not do. */
function sameRawValue(a: unknown, b: unknown): boolean {
  if (a instanceof Date && b instanceof Date) {
    return a.getTime() === b.getTime();
  }
  if (Array.isArray(a) && Array.isArray(b)) {
    return (
      a.length === b.length && a.every((item, i) => sameRawValue(item, b[i]))
    );
  }
  if (typeof a === 'number' && typeof b === 'number') {
    return a === b || (Number.isNaN(a) && Number.isNaN(b));
  }
  return a === b;
}

/** A raw value's text. Dates become ISO — the format that crosses protocols. */
function rawToString(value: unknown): string {
  if (value === null || value === undefined) {
    return '';
  }
  if (value instanceof Date) {
    return Number.isNaN(value.getTime()) ? 'Invalid Date' : value.toISOString();
  }
  return String(value);
}

/** `field()` is stable per class: the same schema for the same value object. */
const FIELD_SCHEMA_CACHE = new WeakMap<object, z.ZodType>();

function registryDecorators(
  schema: z.ZodType,
  registry: DECORATOR_REGISTRY_TYPE = GLOBAL_DECORATOR_REGISTRY,
): Array<PropertyDecorator | ClassDecorator> {
  const decorators: Array<PropertyDecorator | ClassDecorator> = [];
  const own = registry.get(schema);
  if (own && Array.isArray(own.decorators)) {
    decorators.push(
      ...(own.decorators as Array<PropertyDecorator | ClassDecorator>),
    );
  }
  if (registry !== GLOBAL_DECORATOR_REGISTRY) {
    const global = GLOBAL_DECORATOR_REGISTRY.get(schema);
    if (global && Array.isArray(global.decorators)) {
      global.decorators.forEach((decorator) => {
        const typed = decorator as PropertyDecorator | ClassDecorator;
        if (!decorators.includes(typed)) {
          decorators.push(typed);
        }
      });
    }
  }
  return decorators;
}

/** A scalar's `design:type` — what `emitDecoratorMetadata` would emit if the class were written by hand. */
function scalarDesignType(schema: z.ZodType): any {
  let current: z.ZodType = schema;
  while (true) {
    if (current instanceof z.ZodOptional || current instanceof z.ZodNullable) {
      current = current.unwrap() as z.ZodType;
    } else if (current instanceof z.ZodDefault) {
      current = (current._def as any).innerType as z.ZodType;
    } else if (current instanceof z.ZodPipe) {
      current = (current._def as any).out as z.ZodType;
    } else if (current instanceof z.ZodTransform) {
      return Object;
    } else {
      break;
    }
  }

  if (current instanceof z.ZodNumber) return Number;
  if (current instanceof z.ZodString) return String;
  if (current instanceof z.ZodBoolean) return Boolean;
  if (current instanceof z.ZodDate) return Date;
  if (current instanceof z.ZodArray) return Array;
  if (current instanceof z.ZodBigInt) return BigInt;
  return Object;
}

/**
 * Generates a **scalar value object** class from a single-value Zod schema — typically a *branded* one.
 *
 * It is `ValidatedDto`'s sibling: where that one takes an object and generates a class with one field
 * per key, this one takes **a value** and generates a single-field class (`value`) that behaves like
 * that value.
 *
 * ```ts
 * export class PostTitle extends ValidatedDto.Scalar(PostTitleSchema) {
 *   // a rule specific to this class, on top of what the schema already guarantees
 *   isQuestion(): boolean {
 *     return this.value.endsWith('?');
 *   }
 * }
 *
 * PostTitle.parse('  Hi  ').value;           // 'Hi' — normalized by the schema
 * `${new PostTitle('Hi')}`;                  // 'Hi' — toString
 * JSON.stringify({ t: new PostTitle('Hi') }); // {"t":"Hi"} — toJSON
 * ```
 *
 * ## What the class gains
 * `toString` / `toJSON` / `valueOf` / `Symbol.toPrimitive` (the value object *is* the value wherever a
 * value is expected — including in GraphQL scalars, which call `valueOf`/`toJSON` when serializing),
 * `equals` (value equality, not reference equality), `isValid` / `assertValid`, the statics
 * `parse` / `safeParse` / `is` / `accepts`, and `field()`, which embeds the value object into a DTO.
 *
 * ## General rules vs. specific rules
 * The **general** ones live in the Zod schema — it is what normalizes and validates. The **specific**
 * ones arrive through inheritance: new methods (such as `isQuestion` above) or a tighter schema, which
 * the constructor, `parse` and the class-validator validator read dynamically off `this.constructor`.
 *
 * ```ts
 * class HeadlineTitle extends PostTitle.narrow((title) => title.max(40, 'headline too long')) {}
 * ```
 *
 * `narrow` is the typed path: a `HeadlineTitle` is still a `PostTitle`. Overriding `static schema` by
 * hand also works, but then the `brand` has to be re-applied at the end of the chain
 * (`PostTitleSchema.max(40).brand<'PostTitle'>()`) — Zod's refinements do not carry it forward.
 *
 * ## The name comes from the subclass
 * There is no need to supply it: `class PostTitle extends ValidatedDto.Scalar(schema) {}` already
 * produces a class named `PostTitle`, and it is that `constructor.name` that `inspect` and the messages
 * use. The schema's `brand` is **not** good for this — in Zod 4 it is type-only, and `.brand('X')`
 * discards the argument. The `name` option exists for the rare case of using the base without
 * extending it.
 *
 * ## Validating is not throwing
 * The constructor **does not throw** by default — it stores the invalid value for `class-validator` to
 * report, exactly as the object mixin does. For the throwing path, use `VO.parse(...)` (or
 * `{ strict: true }`, which makes `new` throw as well).
 */
export function ValidatedScalar<Schema extends z.ZodType<any, any>>(
  schema: Schema,
  options: ValidatedScalarOptions = {},
): ScalarValueObjectStatic<z.output<Schema>, z.input<Schema>, Schema> {
  type Out = z.output<Schema>;
  type In = z.input<Schema>;

  const {
    name,
    exposeAll = true,
    strict = false,
    DECORATOR_REGISTRY = GLOBAL_DECORATOR_REGISTRY,
    EMBEDDED_REGISTRY: embeddedRegistry = EMBEDDED_REGISTRY,
  } = options;

  if (schema instanceof z.ZodObject) {
    throw new Error(
      'ValidatedDto.Scalar espera um schema de valor único; para um objeto use ValidatedDto.Embeddable',
    );
  }

  class GeneratedScalar {
    /** The schema is static so inheritance can reach it — and override it. */
    static schema: z.ZodType<Out, In> = schema as unknown as z.ZodType<Out, In>;
    static strict = strict;

    readonly value: Out;

    constructor(value: ScalarInput<Out, In>) {
      const ctor = this.constructor as typeof GeneratedScalar;
      const raw = rawScalarValue(value);
      const result = ctor.schema.safeParse(raw);

      if (!result.success && ctor.strict) {
        throw result.error;
      }

      this.value = (result.success ? result.data : raw) as Out;
      this.cacheIssues(this.value, result.success ? undefined : result.error);
    }

    toString(): string {
      return rawToString(this.value);
    }

    toJSON(): any {
      const value = this.value as unknown;
      return value instanceof Date ? value.toISOString() : value;
    }

    valueOf(): Out {
      return this.value;
    }

    [Symbol.toPrimitive](hint: 'number' | 'string' | 'default'): any {
      const value = this.value as unknown;
      if (value instanceof Date) {
        return hint === 'number' ? value.getTime() : value.toISOString();
      }
      if (hint === 'number') return Number(value);
      if (hint === 'string') return this.toString();
      return value;
    }

    /** `console.log(postId)` shows `PostId('uuid')`, not `PostId { value: 'uuid' }`. */
    [INSPECT_CUSTOM](): string {
      return `${this.constructor.name}(${JSON.stringify(this.value)})`;
    }

    /**
     * **Value** equality, within the family: `new PostId(x).equals(new PostId(x))` is `true`, and so is
     * comparing against the raw value. A `TagId` holding the same text is not equal to a `PostId` —
     * which is precisely why the two are different types.
     */
    equals(other: unknown): boolean {
      if (other === null || other === undefined) {
        return false;
      }
      if (isScalarValueObject(other)) {
        const mine = (this.constructor as any)[SCALAR_BASE];
        const theirs = (other.constructor as any)[SCALAR_BASE];
        if (mine !== theirs) {
          return false;
        }
        return sameRawValue(this.value, other.value);
      }
      return sameRawValue(this.value, other);
    }

    isValid(): boolean {
      return this.validationError() === undefined;
    }

    validationError(): z.ZodError | undefined {
      const cached = (this as any)[ISSUE_CACHE];
      if (cached && sameRawValue(cached.for, this.value)) {
        return cached.error;
      }
      const ctor = this.constructor as typeof GeneratedScalar;
      const result = ctor.schema.safeParse(this.value);
      const error = result.success ? undefined : result.error;
      this.cacheIssues(this.value, error);
      return error;
    }

    assertValid(): this {
      const error = this.validationError();
      if (error) {
        throw error;
      }
      return this;
    }

    /** The cache is non-enumerable: it must not leak into `instanceToPlain` nor into `JSON`. */
    private cacheIssues(
      forValue: unknown,
      error: z.ZodError | undefined,
    ): void {
      Object.defineProperty(this, ISSUE_CACHE, {
        value: { for: forValue, error },
        enumerable: false,
        writable: true,
        configurable: true,
      });
    }

    static parse(this: any, value: unknown): any {
      const parsed = this.schema.parse(rawScalarValue(value));
      return this.wrap(parsed);
    }

    static safeParse(this: any, value: unknown): any {
      const result = this.schema.safeParse(rawScalarValue(value));
      return result.success
        ? { success: true, data: this.wrap(result.data) }
        : { success: false, error: result.error };
    }

    /**
     * Wraps a value that has **already passed** through the schema, without parsing again — what `parse`
     * and `field()` use, so that a schema carrying a `.transform()` is not applied twice.
     *
     * A subclass with its own constructor (derived state, for instance) should override this method
     * too; the base has no way of guessing what that constructor does.
     */
    static wrap(this: any, parsed: unknown): any {
      const instance = Object.create(this.prototype);
      instance.value = parsed;
      Object.defineProperty(instance, ISSUE_CACHE, {
        value: { for: parsed, error: undefined },
        enumerable: false,
        writable: true,
        configurable: true,
      });
      return instance;
    }

    static is(this: any, value: unknown): boolean {
      return value instanceof this;
    }

    static narrow(this: any, refine: (schema: any) => any): any {
      const refined = refine(this.schema);
      class NarrowedScalar extends this {
        static schema = refined;
      }
      Object.defineProperty(NarrowedScalar, 'name', {
        value: this.name,
        writable: false,
        enumerable: false,
        configurable: true,
      });
      return NarrowedScalar;
    }

    static accepts(this: any, value: unknown): boolean {
      return this.schema.safeParse(rawScalarValue(value)).success;
    }

    static field(this: any, fieldOptions?: ScalarFieldOptions): z.ZodType {
      const decorators = fieldOptions?.decorators ?? [];
      if (decorators.length === 0) {
        const cached = FIELD_SCHEMA_CACHE.get(this);
        if (cached) {
          return cached;
        }
      }
      const fieldSchema = z
        .unknown()
        .transform((value) => rawScalarValue(value))
        .pipe(this.schema)
        .transform((parsed) => this.wrap(parsed)) as unknown as z.ZodType;

      embeddedRegistry.add(fieldSchema, { kind: 'scalar', target: this });

      if (decorators.length > 0) {
        (fieldOptions?.DECORATOR_REGISTRY ?? DECORATOR_REGISTRY).add(
          fieldSchema,
          {
            decorators,
          },
        );
      } else {
        FIELD_SCHEMA_CACHE.set(this, fieldSchema);
      }
      return fieldSchema;
    }

    /**
     * Copies the base's metadata onto the subclass and applies the registry's decorators.
     *
     * Same job as its namesake in the object mixin, which is why the one `@InheritValidatedMetadata()`
     * serves both — frameworks that inspect the final class (GraphQL, Swagger) see `value` decorated.
     */
    static __copyMetadataToChild(childClass: any): void {
      const childProto = childClass.prototype;
      const parentProto = GeneratedScalar.prototype;

      Reflect.getMetadataKeys(parentProto, 'value').forEach((metadataKey) => {
        Reflect.defineMetadata(
          metadataKey,
          Reflect.getMetadata(metadataKey, parentProto, 'value'),
          childProto,
          'value',
        );
      });

      registryDecorators(schema, DECORATOR_REGISTRY).forEach((decorator) => {
        if (typeof decorator === 'function') {
          (decorator as PropertyDecorator)(childProto, 'value');
        }
      });

      Reflect.getMetadataKeys(GeneratedScalar).forEach((metadataKey) => {
        Reflect.defineMetadata(
          metadataKey,
          Reflect.getMetadata(metadataKey, GeneratedScalar),
          childClass,
        );
      });
    }
  }

  Object.defineProperty(GeneratedScalar.prototype, SCALAR_VALUE_OBJECT, {
    value: true,
    enumerable: false,
    writable: false,
    configurable: false,
  });

  Object.defineProperty(GeneratedScalar, SCALAR_BASE, {
    value: GeneratedScalar,
    enumerable: false,
    writable: false,
    configurable: false,
  });

  Object.defineProperty(GeneratedScalar, 'name', {
    value: name ?? 'ScalarValueObject',
    writable: false,
    enumerable: false,
    configurable: true,
  });

  if (exposeAll) {
    Expose()(GeneratedScalar.prototype, 'value');
  }

  Validate(ZodScalarValidator, [schema])(GeneratedScalar.prototype, 'value');

  Transform(({ value }) => {
    const result = schema.safeParse(rawScalarValue(value));
    return result.success ? result.data : value;
  })(GeneratedScalar.prototype, 'value');

  Reflect.defineMetadata(
    'design:type',
    scalarDesignType(schema),
    GeneratedScalar.prototype,
    'value',
  );

  registryDecorators(schema, DECORATOR_REGISTRY).forEach((decorator) => {
    if (typeof decorator === 'function') {
      (decorator as ClassDecorator)(GeneratedScalar as any);
    }
  });

  (GeneratedScalar as any).__schema = schema;
  (GeneratedScalar as any).__registry = DECORATOR_REGISTRY;

  return GeneratedScalar as unknown as ScalarValueObjectStatic<Out, In, Schema>;
}
